_base_: ["train.yaml"]

model:
  hf_name: "facebook/dinov3-vitl16-pretrain-lvd1689m"
  num_classes: 9

finetune:
  method: "full"

decoder:
  type: "segformer3d"

training:
  lr: 5.0e-5
  batch_size: 1
  grad_accumulation: 8
